account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'
urlpatterns = [
    path("", views.user_login, name="login"),
    path("sign_up", views.sign_up, name="sign_up"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path("user_logout", views.user_logout, name="user_logout"),
    path("profile/", views.profile, name="profile"),
    path("password_reset_request", views.password_reset_request,
         name="password_reset_request"),
    path('useradd', views.useradd, name='useradd'),
    path('userread', views.userread, name='userread'),
    path('userdelete/<int:id>/', views.user_delete, name='userdelete'),
    path('userupdate/<int:id>/', views.user_update, name='userupdate'),
    path("changepass/", views.change_pass, name="change_password"),
]

adminevolution/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('product/', include('product.urls')),
    path('category/', include('category.urls')),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

category/urls.py
from django.urls import path
from . import views


app_name = 'category'
urlpatterns = [
    path('', views.Categoryadd, name='categoryadd'),
    path('categoryread', views.categoryread, name='categoryread'),
    path('categorydelete/<int:id>/', views.category_delete, name='categorydelete'),
    path('categoryupdate/<int:id>/', views.category_update, name='categoryupdate'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.productadd, name='productadd'),
    path('productread', views.productread, name='productread'),
    path('productdelete/<int:id>/', views.product_delete, name='productdelete'),
    path('productupdate/<int:id>/', views.product_update, name='productupdate'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>User Add/Read</title>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" />
  <!-- Font Awesome -->
  {% block csspart %}
  <link rel="stylesheet" href="{%static 'plugins/fontawesome-free/css/all.min.css' %}" />
  <!-- Theme style -->
  <link rel="stylesheet" href="{%static 'dist/css/adminlte.min.css' %}" />
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{%static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}" />
  {% endblock csspart %}
</head>

{% block bodytag %}
{% endblock bodytag%}

{% block nav%}
<div class="wrapper">
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'account:userread' %}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'account:profile' %}" class="nav-link">Profile</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'account:user_logout' %}" class="nav-link">Logout</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'account:change_password' %}" class="nav-link">Change Password</a>
      </li>
    </ul>
  </nav>
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{{user.profile.image.url}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
        style="opacity: 0.8" />
      <span class="brand-text font-weight-light">{{user.full_name}}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{user.profile.image.url}}" class="img-circle elevation-2" alt="User Image" />
        </div>
        <div class="info">
          <a href="{% url 'account:profile' %}" class="d-block">{{user.email}}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search" />
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-users"></i>
              <p>
                USER
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'account:useradd' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add User</p>
                </a>
              </li>
            </ul>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'account:userread' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View User</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-arrow-alt-circle-right"></i>
              <p>
                Product
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'product:productadd' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add Product</p>
                </a>
              </li>
            </ul>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'product:productread' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View Product</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-edit"></i>
              <p>
                Category
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'category:categoryadd' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add Category</p>
                </a>
              </li>
            </ul>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'category:categoryread' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View Category</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  {% endblock nav%}

  {% block bodycontent%}
  {% endblock bodycontent%}

  {% block redirect%}
  {% endblock redirect%}
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2020-2028
      <a href="https://adminlte.io">Bidhya.Pokhrel</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

{% block addjquery %}
<!-- jQuery -->
<script src="{%static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{%static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge("uibutton", $.ui.button);
</script>
<!-- Bootstrap 4 -->
<script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{%static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{%static 'dist/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{%static 'dist/js/demo.js' %}"></script>
<script src="https://kit.fontawesome.com/b45233a9f7.js" crossorigin="anonymous"></script>
{% endblock addjquery %}
</body>

</html>

templates/categoryread.html
{%extends "base.html" %} {% load static %}
<!-- Font Awesome -->

{% block csspart %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
</head>
{% endblock csspart %}

{%block bodycontent%}

<body class="hold-transition sidebar-mini">
  <div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>General Form</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">General Form</li>
                <!-- <li class="breadcrumb-item"><a href="{% url 'account:login' %}">Logout</a></li> -->
              </ol>
            </div>
          </div>
        </div>
        <!-- /.container-fluid -->
        <section class="content">
          <div class="container-fluid">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h3 class="card-title">Category</h3>
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    <table id="example2" class="table table-bordered table-hover">
                      <thead>
                        <tr>
                          <th>Category name</th>
                          <th>vendor</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for categorys in category %}
                        <tr>
                          <td>{{categorys.categoryname}}</td>
                          <td>{{categorys.vendor}}</td>
                          <td>
                            <a href="{% url 'category:categoryupdate' categorys.id %}"
                              class="btn btn-warning btn-sm">Edit</a>
                            <form action="{% url 'category:categorydelete' categorys.id %}" method="POST"
                              class="d-inline">
                              {% csrf_token %}
                              <input type="submit" class="btn btn-danger" value="Delete">
                            </form>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->
              </div>
              <!-- /.col -->
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    {%endblock bodycontent%}

    {%block addjquery%}
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- DataTables  & Plugins -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- Page specific script -->
    <script src="https://kit.fontawesome.com/b45233a9f7.js" crossorigin="anonymous"></script>
    <script>
      $(function () {
        $("#example1").DataTable({
          "responsive": true, "lengthChange": false, "autoWidth": false,
          "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false,
          "responsive": true,
        });
      });
    </script>
    {% endblock addjquery %}
</body>

</html>

templates/categoryupdate.html
{% block content %}
<div class="row">
    <div class="col-sm-8 offset-2">
        <h4 class="alter alter-info">Update Category Information</h4>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <label class="col-sm-2 col-form-label">Category Name:</label>
                    {{form.categoryname}}
                </div>
                <div class="form-group">
                    <label class="col-sm-2 col-form-label">Vendor:</label>
                    {{form.vendor}}
                </div>
            </div>
            <input type="submit" class="btn btn-success" value="Update">
            <a href="{% url 'category:categoryread' %}" class="btn btn-info">Back to Categoryread</a>
        </form>
    </div>
</div>

{% endblock content %}

templates/productadd.html
{%extends "base.html" %} {% load static %}
<!-- Font Awesome -->

{% block csspart %}
<link rel="stylesheet" href="{%static 'plugins/fontawesome-free/css/all.min.css' %}" />
<!-- Theme style -->
<link rel="stylesheet" href="{%static 'dist/css/adminlte.min.css' %}" />
</head>
{% endblock csspart %}

{%block bodycontent%}

<body class="hold-transition sidebar-mini">
  <div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>General Form</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">General Form</li>
                <!-- <li class="breadcrumb-item"><a href="{% url 'account:login' %}">Logout</a></li> -->
              </ol>
            </div>
          </div>
        </div>
        <!-- /.container-fluid -->
      </section>
      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- general form elements -->
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Add Product</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{% url 'product:productadd' %}">
                  {% csrf_token %}
                  <div class="card-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Product Name</label>
                      {{form.productname}}
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail1">Product Quantity</label>
                      {{form.productquantity}}
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail1">Stock</label>
                      {{form.productstock}}
                    </div>
                    <div class="form-group">
                      <label for="exampleInputPassword1">Price</label>
                      {{form.productprice}}
                    </div>
                    <!-- <div class="form-group">
                      <label for="exampleInputFile">Image</label>
                      <div class="input-group">
                        <div class="custom-file">
                          <input type="file" class="custom-file-input" id="exampleInputFile" />
                          <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                      *</div> -->
                  </div>
                  <!-- /.card-body -->

                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">
                      Add Product
                    </button>
                  </div>
                </form>
              </div>
              <!-- /.card -->
            </div>
          </div>
          <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    {%endblock bodycontent%}

    {%block addjquery%}
    <!-- jQuery -->
    <script src="{%static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- bs-custom-file-input -->
    <script src="{%static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{%static 'dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{%static 'dist/js/demo.js' %}"></script>
    <!-- Page specific script -->
    <script src="https://kit.fontawesome.com/b45233a9f7.js" crossorigin="anonymous"></script>
    <script>
      $(function () {
        bsCustomFileInput.init();
      });
    </script>
    {% endblock addjquery %}
</body>

</html>

templates/productread.html
{%extends "base.html" %} {% load static %}
<!-- Font Awesome -->

{% block csspart %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
</head>
{% endblock csspart %}

{%block bodycontent%}

<body class="hold-transition sidebar-mini">
  <div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>General Form</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">General Form</li>
                <!-- <li class="breadcrumb-item"><a href="{% url 'account:login' %}">Logout</a></li> -->
              </ol>
            </div>
          </div>
        </div>
        <!-- /.container-fluid -->
        <section class="content">
          <div class="container-fluid">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h3 class="card-title">Products</h3>
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    <table id="example2" class="table table-bordered table-hover">
                      <thead>
                        <tr>
                          <th>Product Name</th>
                          <th>Product Quantity</th>
                          <th>Stock</th>
                          <th>Price</th>
                          <th>Action</th>

                        </tr>
                      </thead>
                      <tbody>
                        {% for products in product %}
                        <tr>
                          <td>{{products.productname}}</td>
                          <td>{{products.productquantity}}</td>
                          <td>{{products.productstock}}</td>
                          <td>{{products.productprice}}</td>
                          <td>
                            <a href="{% url 'product:productupdate' products.id %}"
                              class="btn btn-warning btn-sm">Edit</a>
                            <form action="{% url 'product:productdelete' products.id %}" method="POST" class="d-inline">
                              {% csrf_token %}
                              <input type="submit" class="btn btn-danger" value="Delete">
                            </form>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->
              </div>
              <!-- /.col -->
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    {%endblock bodycontent%}

    {%block addjquery%}
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- DataTables  & Plugins -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- Page specific script -->
    <script src="https://kit.fontawesome.com/b45233a9f7.js" crossorigin="anonymous"></script>
    <script>
      $(function () {
        $("#example1").DataTable({
          "responsive": true, "lengthChange": false, "autoWidth": false,
          "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false,
          "responsive": true,
        });
      });
    </script>
    {% endblock addjquery %}
</body>

</html>

templates/productupdate.html
{% block content %}
<div class="row">
    <div class="col-sm-8 offset-2">
        <h4 class="alter alter-info">Update Product Information</h4>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <label class="col-sm-2 col-form-label">Product Name:</label>
                    {{form.productname}}
                </div>
                <div class="form-group">
                    <label class="col-sm-2 col-form-label">Product Quantity:</label>
                    {{form.productquantity}}
                </div>
                <div class="form-group">
                    <label class="col-sm-2 col-form-label">Stock:</label>
                    {{form.productstock}}
                </div>
                <div class="form-group">
                    <label class="col-sm-2 col-form-label">Price:</label>
                    {{form.productprice}}
                </div>
            </div>
            <input type="submit" class="btn btn-success" value="Update">
            <a href="{% url 'product:productread' %}" class="btn btn-info">Back to Productread</a>
        </form>
    </div>
</div>

{% endblock content %}

templates/userlogin.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Login Page </title>
    <style>
        Body {
            font-family: Calibri, Helvetica, sans-serif;
            background-color: rgb(207, 203, 203);
        }

        button {
            background-color: #4CAF50;
            width: 100%;
            color: orange;
            padding: 15px;
            margin: 10px 0px;
            border: none;
            cursor: pointer;
        }

        form {
            border: 3px solid #f1f1f1;
        }

        input[type=email] input[type=password] {
            width: 100%;
            margin: 8px 0;
            padding: 12px 20px;
            display: inline-block;
            border: 2px solid green;
            box-sizing: border-box;
        }

        button:hover {
            opacity: 0.7;
        }

        .cancelbtn {
            width: auto;
            padding: 10px 18px;
            margin: 10px 5px;
        }


        .container {
            padding: 25px;
            background-color: lightblue;
        }
    </style>
</head>

<body>
    <center>
        <h1>User Login Form</h1>
    </center>

    {% for message in messages %}
    <div class="alert alert-{{message.tags}} mt-2" role="alert">
        {{message}}
    </div>
    {% endfor %}
    <form action="{% url 'account:login'%}" method="post">
        {% csrf_token %}
        <div class="container">
            {{form|crispy}}
            <button type="submit">Login</button>
            <input type="checkbox" checked="checked"> Remember me
            <a href="{% url 'account:sign_up' %}" class="btn btn-info">Don't have an account?</a>
            Forgot <a href="{% url 'account:password_reset_request' %}">Forgot your password? </a>
        </div>
    </form>
</body>

</html>




<!-- <form action="" method="post" novalidate>
    {% csrf_token %}
    {{form|crispy}}

    <a href="{% url 'account:sign_up' %}" class="btn btn-info">Don't have an account?</a>
    <a href="{% url 'account:login' %}" input type="submit" value="Login">
</form>
</body>

</html> -->






<!-- <div class="wrapper">
    <form class="login" action="" method="POST" novalidate>
        {% csrf_token %}
        <p class="title">Log in</p>
        <label for="id_username">Username</label>
        <input type="input" placeholder="Username" autofocus />
        <i class="fa fa-user"></i>
        <label for="id_password">Password</label>
        <input type="password" placeholder="Password" />
        <i class="fa fa-key"></i>
        <a href="{% url 'account:sign_up' %}" class="btn btn-info">Don't have an account?</a>
        <button>
            <i class="spinner"></i>
            <span class="state">Log in</span>
        </button>
    </form>
    </p>
</div> -->